### ISSUE TITLE
Something wrong when I ran the code

### ISSUE THREAD

**Issue by 00ohnim** [neufieldrobotics/NeuFlow_v2#2]
Hi,I met the problem ,do you know how to solve it?
python train.py --stage sintel --val_dataset kitti --checkpoint_dir /home/xu/wyh/NeuFlow_v2/checkpoint --distributed
Use 2 GPUs
Number of params: 9029536
20820 20820 0 0 0
Number of training images: 41640
Traceback (most recent call last):
  File "train.py", line 246, in <module>
    main(args)
  File "train.py", line 147, in main
    for i, sample in enumerate(train_loader):
  File "/home/xu/anaconda3/envs/neuflow/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 633, in __next__
    data = self._next_data()
  File "/home/xu/anaconda3/envs/neuflow/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 677, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/xu/anaconda3/envs/neuflow/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/xu/anaconda3/envs/neuflow/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/xu/anaconda3/envs/neuflow/lib/python3.8/site-packages/torch/utils/data/dataset.py", line 244, in __getitem__
    return self.datasets[dataset_idx][sample_idx]
  File "/home/xu/anaconda3/envs/neuflow/lib/python3.8/site-packages/torch/utils/data/dataset.py", line 244, in __getitem__
    return self.datasets[dataset_idx][sample_idx]
  File "/home/xu/anaconda3/envs/neuflow/lib/python3.8/site-packages/torch/utils/data/dataset.py", line 244, in __getitem__
    return self.datasets[dataset_idx][sample_idx]
  [Previous line repeated 1 more time]
  File "/home/xu/wyh/NeuFlow_v2/data_utils/datasets.py", line 70, in __getitem__
    flow = frame_utils.read_gen(self.flow_list[index])
IndexError: list index out of range

**Comment by 00ohnim** [comment]
sorry ，seems the root is wrong

**Comment by Study-is-happy** [comment]
Symlink your dataset root to `datasets`:

```shell
ln -s $YOUR_DATASET_ROOT datasets
```
